# Thanks For Downloading Battleground! Let me know what you think! #

usePermissions: true

dominationMaxPlayers: 30

dominationPlayersToStart: 10

dominationWinReward:
   MaterialId: 264
   Amount: 5



